apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: application-hpa
  labels:
    app: employees
    component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 3
  
  
  
  # metrics:
  #   - type: Resource
  #     resource:
  #       name: cpu
  #       target:
  #         type: Utilization
  #         averageUtilization: 3
